### ISSUE TITLE
0.4.9 fatal error 'ProcessBuilder not found'

### ISSUE THREAD

**Issue by AaronHolbrook** [alchemy-fr/Zippy#142]
`v0.4.8` still works fine, but upgrading to `0.4.9` and then running this exact code gives me a fatal error.

Here's how I'm using Zippy:

```php
use Alchemy\Zippy\Zippy;
use function Zeek\PHP_Util\rrmdir;

/**
 * Load all the composer packages
 */
require_once __DIR__ . '/vendor/autoload.php';

function generate_zip_file() {

	$toolkit_filename = 'toolkit.zip';

	$vendor_dir = __DIR__ . '/vendor';

	// Creates an archive.zip that contains a directory "folder" that contains
	// files contained in "/path/to/directory" recursively
	$zippy = Zippy::load();

	// Make our tmp directory
	if ( ! file_exists( __DIR__ . '/tmp' ) ) {
		mkdir( __DIR__ . '/tmp' );
	}

	$paths = [
		'index',
		'buttons',
		'breadcrumbs',
	];

	foreach ( $paths as $path ) {
		generate_path_html( $path );
	}

	$archive = $zippy->create( $toolkit_filename, [
		'vendor'       => $vendor_dir,
		'index.html'   => __DIR__ . '/tmp/index.html',
		'buttons.html' => __DIR__ . '/tmp/buttons.html',
	], true );

	// Remove the tmp directory
	rrmdir( __DIR__ . '/tmp' );
}

function generate_path_html( $path = 'index' ) {
	ob_start();

	echo shell_exec( 'php index.php ' . $path );

	$path_html = ob_get_clean();

	file_put_contents( "tmp/{$path}.html", $path_html );
}

generate_zip_file();

die;
```

And here's the error:

```
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Process\ProcessBuilder' not found in /dev/sites/example/htdocs/vendor/alchemy/zippy/src/ProcessBuilder/ProcessBuilderFactory.php:69
Stack trace:
#0 /dev/sites/example/htdocs/vendor/alchemy/zippy/src/Adapter/VersionProbe/ZipVersionProbe.php(70): Alchemy\Zippy\ProcessBuilder\ProcessBuilderFactory->create()
#1 /dev/sites/example/htdocs/vendor/alchemy/zippy/src/Adapter/AbstractAdapter.php(146): Alchemy\Zippy\Adapter\VersionProbe\ZipVersionProbe->getStatus()
#2 /dev/sites/example/htdocs/vendor/alchemy/zippy/src/Zippy.php(156): Alchemy\Zippy\Adapter\AbstractAdapter->isSupported()
#3 /dev/sites/example/htdocs/vendor/alchemy/zippy/src/Zippy.php(67): Alchemy\Zippy\Zippy->getAdapterFor('zip')
#4 /dev/sites/example/htdocs/script.php(42): Alchemy\Zippy\Zippy->create('toolkit.zip', Array, true)
#5 /dev/sites/example/htdocs/script.php(58): ETT\g in /dev/sites/example/htdocs/vendor/alchemy/zippy/src/ProcessBuilder/ProcessBuilderFactory.php on line 69
```

**Comment by eddturtle** [comment]
I'm getting this error too, have tried running `composer dump-autoload` but hasn't helped. Had a look through the code and couldn't see the issue. Also using version `0.4.9`.

**Comment by luceos** [comment]
Seems the pr #140 actually broke this package completely. The complete symfony/process signature changes. I'm preparing a PR.

**Comment by wilsmex** [comment]
Having the same issue and error here `Uncaught Error: Class 'Symfony\Component\Process\ProcessBuilder' not found`

Updating broke all of my zippy code...

**Comment by bastien-phi** [comment]
ProcessBuilder was deprecated in symfony/component 3.4.0 and removed in symfony/component 4.0
see https://github.com/symfony/process/blob/master/CHANGELOG.md

**Comment by launay12u** [comment]
Someone has information about the progress of this issue, I still have the problem but I saw that a PR was open to solve this problem, will it soon be merge?

**Comment by adammfrank** [comment]
Is this library just broken and dead?

**Comment by wapmorgan** [comment]
ProcessBuilder is not available in symfony/process 4.
Need to upgrade zippy to cover this case.

Example of fixing this case in another project - https://github.com/pact-foundation/pact-php/pull/61/files

**Comment by wapmorgan** [comment]
@luceos Are you a maintainer of this package?

**Comment by vouza** [comment]
As I had to upgrade Symfony and the maintainers of the project stopped to "maintain", I had no choice other than creating a nasty patch, that allows to use the zipper by ignoring the "ZipVersionProbe" functionality. I do not know the ZipVersionProbe class it is meant to do as I can't afford to spend more time with researching. With me it works.

Maybe this is a small help to somebody who runs into the same issue.


`--- src/Adapter/VersionProbe/ZipVersionProbe.php	2018-02-22 14:58:36.000000000 +0100
+++ src/Adapter/VersionProbe/ZipVersionProbe.php	2021-03-02 18:03:18.000000000 +0100
@@ -65,6 +65,8 @@
             return $this->isSupported = VersionProbeInterface::PROBE_NOTSUPPORTED;
         }

+        return $this->isSupported = VersionProbeInterface::PROBE_NOTSUPPORTED;
+
         $processDeflate = $this
             ->deflator
             ->create()
`

**Comment by luceos** [comment]
> @luceos Are you a maintainer of this package?
> Right now the only way to fix is to require symfony/process with version `symfony/process": "^2.1 || ^3.0"`

I'm not. And I don't remember using this in my apps anymore.

If you need this, I highly suggest forking and adding a link to the fork here.
